name: Docker CI/CD Pipeline

on:
  push:
    branches: [ add-unit-tests, main ]
  pull_request:
    branches: [ add-unit-tests, main ]

jobs:
    build-test-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Python3
          uses: actions/setup-python@v3
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: |
            pytest tests/

        - name: Build Docker image
          run: |
            docker build -t footballer_pulse .

        - name: Push Docker image to DockerHub
          if: github.ref == 'refs/heads/main'
          run: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker tag footballer_pulse:latest ${{ secrets.DOCKERHUB_USERNAME }}/footballer_pulse:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/footballer_pulse:latest